name: .NET

on:
  push:
    branches:
      - '**'

jobs:
  ## Only build nuget package and release to Nuget.org when running on main branch
  dotnet_pack_release_job:
    uses: HBDStack/ShareWorkflows/.github/workflows/dotnet-package-release.yml@main
    with:
      Project_Path: 'HBDStack.EfCore.Extensions.sln'
      Enable_Release: ${{ github.ref == 'refs/heads/main' }}
      Enable_Nuget_Release: ${{ github.ref  == 'refs/heads/main'}}
    secrets:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      NUGET_PACKAGE_TOKEN: ${{ secrets.NUGET_PACKAGE_TOKEN }}
      
  dotnet_sonar_scan:
    uses: HBDStack/ShareWorkflows/.github/workflows/sonar-build.yml@main
    with:
      Project_Path: 'HBDStack.EfCore.Extensions.sln'
      Project_Name: 'HBDStack_HBDStack.EfCore.Extensions'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
